enum VideoActionType {
  SEARCH_VIDEOS_REQUEST = "SEARCH_VIDEOS_REQUEST",
  SEARCH_VIDEOS_SUCCEEDED = "SEARCH_VIDEOS_SUCCEEDED",
  SEARCH_VIDEOS_FAILED = "SEARCH_VIDEOS_FAILED",
}

export default VideoActionType;
